import './globals.css'


export const metadata = {
  title: 'Interactive App',
  description: 'An interactive app for friends',
  keywords: 'chat, Webapp, webdesign',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       {children}
      </body>
    </html>
  )
}


//you can create metadatas in any page. Metadatas can have keyword field which can have words that can help improve the search engine optimization.
// export const metadata = {
  // title: 'Interactive App',
  // description: 'Generated by create next app',
  // keyword: chat gjhgfdbhj, bggjdsgf, jhgsdtfgd,
// }